version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: videowall-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: videowall
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: videowall
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videowall"]
      interval: 10s
      timeout: 5s
      retries: 5

  livekit:
    image: livekit/livekit-server:latest
    container_name: videowall-livekit
    restart: unless-stopped
    command: --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml:ro
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50020:50000-50020/udp"
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videowall-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://videowall:${POSTGRES_PASSWORD:-changeme}@postgres:5432/videowall
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - LIVEKIT_URL=${LIVEKIT_URL:-ws://livekit:7880}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-devkey}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-secret}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      livekit:
        condition: service_started

volumes:
  postgres_data:
