version: '3.9'

services:
    livekit:
    image: livekit/livekit-server:latest
    container_name: videowall-livekit
    restart: unless-stopped
    command: --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml:ro
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50020:50000-50020/udp"
    depends_on:
      - postgres