version: '3.9'

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /livekit.yaml
    volumes:
      - ./livekit.yaml:/livekit.yaml:ro
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-60000:50000-60000/udp"
    restart: unless-stopped