services:
  postgres:
    image: postgres:16-alpine
    container_name: videowall-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: videowall
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: videowall
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videowall"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
